### ISSUE TITLE
Review foundational literature and science behind bio-acoustics

### ISSUE THREAD

**Issue by vaibhavmehrotraml** [orcasound/ambient-sound-analysis#38]
```[tasklist]
### Tasks
- [ ] Review default fft transformation in libros
```

**Comment by scottveirs** [comment]
Here are two resources that may be helpful:

- Introductory materials for computing dB levels from audio signals
  - [Discovery of Sound in the Sea](https://dosits.org/) (DOSITS educational website for bioacoustics)
    - Start with: [How is sound measured?](https://dosits.org/science/measurement/)
    - Don’t miss: [How are sounds viewed and analyzed?](https://dosits.org/science/measurement/how-are-sounds-viewed-and-analyzed/) 
  - Also, read through: [Advanced topics](https://dosits.org/science/advanced-topics/)

There is also this [SRKW Zotero library](https://www.zotero.org/groups/7919/southern_resident_killer_whales/library) you are welcome to join if you want quick access to much of the literature related to orca and ship bioacoustics.

**Comment by zprice12** [comment]
Reviewed and completed
