### ISSUE TITLE
Extrapolate results to predict cost of running on larger datasets

### ISSUE THREAD

**Issue by vaibhavmehrotraml** [orcasound/ambient-sound-analysis#42]

**Comment by zprice12** [comment]
Predicted running a month's worth of data at 1s 1hz.
<img width="351" alt="Screen Shot 2024-03-11 at 12 07 49 PM" src="https://github.com/orcasound/ambient-sound-analysis/assets/118499445/2dec1212-bdec-489f-9db3-31b17a63b80a">
