### ISSUE TITLE
Tailor Conversion to Work with British Columbia Hydrophone Network’s Open Bioacoustics Dashboard

### ISSUE THREAD

**Issue by vaibhavmehrotraml** [orcasound/ambient-sound-analysis#43]

**Comment by vaibhavmehrotraml** [comment]
Computing a recent month of data from at least one Orcasound location in the frequency bands that the BC Hydrophone Network is using within the open bioacoustics dashboard (e.g. using example of input csv files from Ben).

**Comment by zprice12** [comment]
Stretch goal not completed by current capstone group
