### ISSUE TITLE
Parallelize existing codebase to optimize for cost

### ISSUE THREAD

**Issue by vaibhavmehrotraml** [orcasound/ambient-sound-analysis#47]

**Comment by ttan06** [comment]
![Image](https://github.com/orcasound/ambient-sound-analysis/assets/118499308/c9530bc3-2ab1-46f4-959a-c70c8635804a)

Running into index out of range using "fast" mode

**Comment by zprice12** [comment]
Downloading process is completely parallelized. Fixing of fast mode still a work in progress, won't be completed by current capstone group
