### ISSUE TITLE
Add broadband as 0 Column in PDS dataframes.

### ISSUE THREAD

**Issue by CaseCal** [orcasound/ambient-sound-analysis#9]
As per discussion, the broadband value should be appended as the 0 column to the generated PDS dataframes. 

There is currently a 0 column representing the lowest band, do we need to rename the column values to the middle or top of each band?

**Comment by mitchhaldeman** [comment]
wav_to_array returns the broadband result as a separate dataframe right now.  We could easily just change that function to return one df with the broadband result as column 0.

**Comment by CaseCal** [comment]
After discussion, broadband will not be included. It is available to produce both on-demand or easily calculable from a more granular parquet artifact, so its a minor gain to pre-calculate compared to the added complexity of parsing and documenting the generated files.

**Comment by scottveirs** [comment]
That makes sense to me. Good call.

@veirs may want to chime in with a differing opinion, but I say proceed!
